---
- name: Preparar ambiente Python
  hosts: vm
  become: true
  gather_facts: false
  tasks:
    - name: Remover script problemático
      raw: rm -f /usr/lib/cnf-update-db

    - name: Atualizar cache do apt
      raw: DEBIAN_FRONTEND=noninteractive apt-get update -qq

    - name: Instalar Python 3.9
      raw: apt-get install -y python3.9 python3.9-distutils

    - name: Instalar python3-apt
      raw: apt-get install -y python3-apt

    - name: Instalar pip para Python 3.9
      raw: apt-get install -y python3.9-pip

    - name: Instalar python-apt via pip para Python 3.9
      raw: python3.9 -m pip install python-apt --quiet

    - name: Criar symlink para python3
      raw: update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1

- name: Instalar Docker no Ubuntu
  hosts: vm
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
    - name: Instalar dependências
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Adicionar repositório do Docker (deb822)
      deb822_repository:
        name: docker
        types: [deb]
        uris: https://download.docker.com/linux/ubuntu
        suites: ["{{ ansible_distribution_release }}"]
        components: [stable]
        signed_by: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Atualizar cache do apt e instalar Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Adicionar usuário ao grupo Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Iniciar e habilitar serviço Docker
      systemd:
        name: docker
        state: started
        enabled: yes
        
    - name: Executar container da aplicação Java
      docker_container:
        name: java-api
        image: iesodias/java-api:latest
        state: started
        restart_policy: always
        published_ports:
          - "8081:8081"